In [19]:
import numpy as np
import time
import os#/sys
#a = np.array([(1,2,3),(4,5,6)])
#print(a)

In [9]:
os.getcwd()
os.chdir('C:\\Users\\VJ')

In [10]:
os.getcwd()

'C:\\Users\\VJ'

In [25]:
time.ctime()

'Sun Jan 19 10:43:49 2020'

In [24]:
a = np.array([(1,2,3),(4,5,6)])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
rang = range(1,10)
print(rang)
nrang = np.arange(1,10)
print(nrang)

range(1, 10)
[1 2 3 4 5 6 7 8 9]


In [16]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [26]:
a = 10


28

In [7]:
S = range(1000)
D = np.arange(1000)
print(sys.getsizeof(5)*len(S))
print(D.size*D.itemsize)

28000
4000


In [19]:
import os as a
a.getcwd()

'C:\\Users\\VJ'

In [10]:
SIZE = 1000
L1 = range(SIZE)
L2 = range(SIZE)
A1 = np.arange(SIZE)
A2 = np.arange(SIZE)
start = time.time()

result = [(x,y) for x,y in zip(L1,L2)]
print((time.time()-start)*1000)

start =time.time()

result = A1 +A2
print((time.time()-start)*1000)


0.0
0.9970664978027344


In [47]:
a = np.array([(1,2,3,5,6),(4,5,6,1,3),(7,8,9,1,3),(7,8,9,8,6),(7,8,9,8,6)])
print(a.shape)

(5, 5)


In [36]:
print(a.ravel())

[1 2 3 5 6 4 5 6 1 3 7 8 9 1 3 7 8 9 8 6 7 8 9 8 6]


In [38]:
print(a.reshape(1,25))

[[1 2 3 5 6 4 5 6 1 3 7 8 9 1 3 7 8 9 8 6 7 8 9 8 6]]


In [31]:
a = np.array([(1,2,3),(4,5,6)])
print(a)

[[1 2 3]
 [4 5 6]]


In [26]:
print(a[0][2])

3


In [40]:
a

array([[1, 2, 3, 5, 6],
       [4, 5, 6, 1, 3],
       [7, 8, 9, 1, 3],
       [7, 8, 9, 8, 6],
       [7, 8, 9, 8, 6]])

In [44]:
a.sum(axis =1)

array([17, 19, 28, 38, 38])

In [37]:
print(np.linspace(1,2,10))

[1.         1.11111111 1.22222222 1.33333333 1.44444444 1.55555556
 1.66666667 1.77777778 1.88888889 2.        ]


In [38]:
print(a.sum())

38


In [36]:
a = np.array([(1,2,3),(4,5,6)])
print(a)
print("axis sum")
print(a.sum(axis=1))

[[1 2 3]
 [4 5 6]]
axis sum
[ 6 15]


In [38]:
print(np.min(a))
print(np.max(a))
print(np.mean(a))
print(np.std(a))
print(np.median(a))

1
6
3.5
1.707825127659933
3.5


In [48]:
a = np.array([(1,2,3),(4,5,6)])
b = np.array([(1,2,3),(4,5,6)])

c = a*b
print(c)

[[ 1  4  9]
 [16 25 36]]


In [49]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
a**2

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

In [58]:
np.zeros(10)+5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [59]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [69]:
np.eye(10)-5

array([[-4., -5., -5., -5., -5., -5., -5., -5., -5., -5.],
       [-5., -4., -5., -5., -5., -5., -5., -5., -5., -5.],
       [-5., -5., -4., -5., -5., -5., -5., -5., -5., -5.],
       [-5., -5., -5., -4., -5., -5., -5., -5., -5., -5.],
       [-5., -5., -5., -5., -4., -5., -5., -5., -5., -5.],
       [-5., -5., -5., -5., -5., -4., -5., -5., -5., -5.],
       [-5., -5., -5., -5., -5., -5., -4., -5., -5., -5.],
       [-5., -5., -5., -5., -5., -5., -5., -4., -5., -5.],
       [-5., -5., -5., -5., -5., -5., -5., -5., -4., -5.],
       [-5., -5., -5., -5., -5., -5., -5., -5., -5., -4.]])

In [61]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
np.exp(a)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [54]:
print(np.vstack(a))

[[1 2 3]
 [4 5 6]]


In [68]:
import matplotlib.pyplot as mat
x = np.arange(0,3*np.pi)
print(3*np.pi)


[]


C:\Users\VJ\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DeprecationWarning: object of type <class 'float'> cannot be safely interpreted as an integer.
  This is separate from the ipykernel package so we can avoid doing imports until


In [58]:
print(np.exp(a))

[[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]


In [62]:
print(np.log(a))

[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]]


In [12]:
import numpy as np
np.zeros(10).reshape(2,5) + 5 

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [10]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [2]:
import numpy as np
np.arange(0,1,0.01)

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99])

In [12]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [13]:
import random as rd

In [15]:
rd.random()

0.28741415276112137

In [23]:
np.random.seed(10)
np.random.rand(1)

array([0.77132064])

In [26]:
np.random.seed(74)
np.random.randint(low = 0, high = 100, size = 5)

array([30, 91,  9, 73, 62])

In [25]:
np.random.seed(0)
np.random.randint(low = 0, high = 100, size = 5)

array([44, 47, 64, 67, 67])

In [3]:
li = [5, 7, 22, 97, 54, 62, 77, 23, 73, 61] 
final_list = list(filter(lambda x: (x%2 == 0) , li)) 
print(final_list) 

[22, 54, 62]


In [7]:
import numpy as np

In [16]:
mat = np.arange(1,27).reshape(13,2)
mat

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20],
       [21, 22],
       [23, 24],
       [25, 26]])

array([1, 2, 3, 4, 5])

In [70]:
import pandas as pd

In [73]:
a = np.arange(1,101).reshape(25,4)

In [75]:
a.shape

(25, 4)

In [76]:
pd.DataFrame(a)

0   1   2    3
0    1   2   3    4
1    5   6   7    8
2    9  10  11   12
3   13  14  15   16
4   17  18  19   20
5   21  22  23   24
6   25  26  27   28
7   29  30  31   32
8   33  34  35   36
9   37  38  39   40
10  41  42  43   44
11  45  46  47   48
12  49  50  51   52
13  53  54  55   56
14  57  58  59   60
15  61  62  63   64
16  65  66  67   68
17  69  70  71   72
18  73  74  75   76
19  77  78  79   80
20  81  82  83   84
21  85  86  87   88
22  89  90  91   92
23  93  94  95   96
24  97  98  99  100