In [ ]:
import numpy as np

In [ ]:
a = np.array([(1,2,3),(4,5,6)])

In [31]:
b = np.arange(0,15).reshape(5,3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [ ]:
a.size


In [ ]:
a.shape

In [29]:
range(0,5)

range(0, 5)

In [27]:
np.arange(0,5,0.2)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8])

In [ ]:
import time

size = 1000000

L1 = range(size)
L2 = range(size)

A1 = np.arange(size)
A2 = np.arange(size)

In [ ]:
a

In [ ]:
b = a.reshape(3,2)

In [ ]:
b

In [ ]:
a[1]

In [ ]:
a[0:,2]

In [1]:
np.arange(0,10,3)

NameError: name 'np' is not defined

In [ ]:
c = np.linspace(1,10,5)
c

In [ ]:
a.sum()

In [ ]:
a

In [ ]:
a.sum(axis=0)

In [ ]:
a.sum(axis=1)

In [ ]:
np.sqrt(a)

In [ ]:
np.std(a)

In [ ]:
a = np.array([(1,2,3),(4,5,6)])
b = np.array([(5,7,3),(4,5,6)])

c = np.vstack((a,b))
c

In [ ]:
a

In [ ]:
a.ravel()

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt

x = np.arange(0,3*np.pi,0.1)

y = np.sin(x)

plt.plot(x,y)
plt.show()

In [ ]:
np.exp(a)

In [ ]:
np.log(a)

In [ ]:
np.arange(1,10)

In [ ]:
np.linspace(5,10,1)

In [41]:
np.zeros((3,4),np.uint8)*21

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=uint8)

In [50]:
a = np.ones((3,4))+5

In [52]:
a/6

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [48]:
np.eye(3,3)+1

array([[2., 1., 1.],
       [1., 2., 1.],
       [1., 1., 2.]])