In [1]:
import numpy as np

In [21]:
b=np.array([(9,8,7),(5,9,9),(66,67,68)])
b

array([[ 9,  8,  7],
       [ 5,  9,  9],
       [66, 67, 68]])

In [3]:
a=np.array([(1,2,3),(4,5,6),(5,8,9)])
a

array([[1, 2, 3],
       [4, 5, 6],
       [5, 8, 9]])

In [22]:
a.size
b.size

9

In [23]:
a.shape
b.shape

(3, 3)

In [10]:
#arange function for numpy
# start end and interval in numpy same as range funcion in python
np.arange(0,6,0.2)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. ,
       5.2, 5.4, 5.6, 5.8])

In [4]:
a.sum()

43

In [24]:
a.sum(axis=0)
b.sum(axis=0)

array([80, 84, 84])

In [25]:
a.sum(axis=1)
b.sum(axis=1)

array([ 24,  23, 201])

In [26]:
c=np.arange(0,15).reshape(5,3)
c

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [86]:
c=np.arange(0,15).reshape(3,5)
c

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [13]:
# to determine that numpy array takes less time as comparison to list 
import time
size=10000
L1=range(size)
L2=range(size)
A1=np.arange(size)
A2=np.arange(size)
start=time.time()
result=[(x,y) for x,y in zip(L1,L2)]
print((time.time()-start)*1000)

4.9991607666015625


In [14]:
start=time.time()
start

1583119891.6214552

In [15]:
start=time.time()
result=A1+A2
print((time.time()-start)*1000)

2.000570297241211


In [83]:
b=a.reshape(3,2)
b

array([[55, 67],
       [78, 67],
       [88, 90]])

In [19]:
a[1]

array([4, 5, 6])

In [43]:
a[0:,2]

array([3, 6, 9])

In [48]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [50]:
c=np.linspace(1,10,5)
c

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [51]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.23606798, 2.82842712, 3.        ]])

In [52]:
np.mean(a)

4.777777777777778

In [53]:
np.std(a)

2.4845199749997664

In [55]:
a=np.array([(1,2,3),(4,5,6)])
b=np.array([(6,7,8),(7,8,9)])
c=np.hstack((a,b))
c

array([[1, 2, 3, 6, 7, 8],
       [4, 5, 6, 7, 8, 9]])

In [56]:
a=np.array([(55,67,78),(67,88,90)])
b=np.array([(4,5,6),(5,7,8)])
c=np.vstack((a,b))
c

array([[55, 67, 78],
       [67, 88, 90],
       [ 4,  5,  6],
       [ 5,  7,  8]])

In [57]:
a.ravel()

array([55, 67, 78, 67, 88, 90])

In [58]:
b.ravel()

array([4, 5, 6, 5, 7, 8])

In [60]:
np.exp(a)

array([[7.69478527e+23, 1.25236317e+29, 7.49841700e+33],
       [1.25236317e+29, 1.65163625e+38, 1.22040329e+39]])

In [61]:
np.log(a)

array([[4.00733319, 4.20469262, 4.35670883],
       [4.20469262, 4.47733681, 4.49980967]])

In [62]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [67]:
np.zeros((3,4),np.uint8)*21

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=uint8)

In [68]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [71]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [72]:
np.ones((3,4))+8

array([[9., 9., 9., 9.],
       [9., 9., 9., 9.],
       [9., 9., 9., 9.]])

In [73]:
np.ones((3,4))/8

array([[0.125, 0.125, 0.125, 0.125],
       [0.125, 0.125, 0.125, 0.125],
       [0.125, 0.125, 0.125, 0.125]])

In [75]:
np.ones((5,6))-2

array([[-1., -1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1., -1.]])

In [78]:
np.eye(3,3)

array([[4., 3., 3.],
       [3., 4., 3.],
       [3., 3., 4.]])

In [79]:
np.eye(3,3)+8

array([[9., 8., 8.],
       [8., 9., 8.],
       [8., 8., 9.]])

In [88]:
L=np.arange(5)
L

array([0, 1, 2, 3, 4])

In [89]:
L=[]
for i in range(5):
    L.append(i)
L

[0, 1, 2, 3, 4]

In [95]:
# to find dimentional of the array
a=np.array([(1,2,3),(4,5,6)])
print(a.ndim)
# to determine the each element size in bytes
print(a.itemsize)
# to find the data types of array
print(a.dtype)
# to find the size of an array
print(a.size)
print(a.shape)

2
4
int32
6
(2, 3)


In [96]:
a=np.array([(1,2,3),(4,5,6)])
a=a.reshape(3,2)
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [99]:
a=np.linspace(1,3,5)
print(a)

[1.  1.5 2.  2.5 3. ]


In [117]:
a=np.array([(1,2,3),(4,5,6)])
print(a[0:2,2])
a=np.sum(a)
a

[3 6]


21

In [118]:
a=np.array([1,2,3])
a.max()

3

In [119]:
a.min()

1

In [120]:
a.sum()

6

In [121]:
# for rows(axis=1)
# for columns(axis=0)
a=np.array([(1,2,3),(4,5,6)])
a.sum(axis=0)

array([5, 7, 9])

In [122]:
#1,2,3
#4,5,6
a.sum(axis=1)

array([ 6, 15])

In [126]:
print(a.shape)

(2, 3)


In [129]:
np.arange(0,1,0.01)

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99])

In [130]:
import numpy as np
import time
import os
os.getcwd()

'C:\\Users\\Admin\\Anaconda32'

In [133]:
#os.chdir()
time.ctime()

'Mon Mar  2 17:56:38 2020'

In [134]:
import random as rd

In [135]:
rd.random()

0.2834397510971849

In [6]:
import numpy as np
print(np.random.seed(30))
np.random.rand(1)

None


array([0.64414354])

In [8]:
np.random.randint(low=0, high=100,size=5)

array([53, 17, 46,  3, 41])

In [3]:
import random as rd
import numpy as np

In [4]:
np.random.random(5)

array([0.85324292, 0.31028266, 0.24202657, 0.29088034, 0.09488398])

In [6]:
np.random.randn(2,1,3)

array([[[ 0.7783131 , -0.69777665, -0.29585155]],

       [[ 1.41661568, -1.13324535,  0.61730599]]])

In [7]:
np.random.randint(low=0, high=100, size=10)

array([48, 85, 62, 64, 19, 99, 57, 77, 46,  8])

In [8]:
np.random.rand(4)

array([0.79618396, 0.89689204, 0.04688479, 0.05983376])

In [ ]:
# random functions
#random
#randn
#randint
#rand

# Numpy and Pandas example
# Series loc and Panel function

In [13]:
round(3.14,12)

3.14

In [22]:
import pandas as pd
import numpy as np
data=np.array(['a','b','c','d'])
s=pd.Series(data)
print(s)

0    a
1    b
2    c
3    d
dtype: object


In [27]:
df=pd.DataFrame([[1,2],[3,4],[5,6]],
index=['cobra','viper','sidewinder'],
columns=['max speed','shield'])
print(df)

            max speed  shield
cobra               1       2
viper               3       4
sidewinder          5       6


In [32]:
df.loc[['viper','sidewinder']]
df['viper']

max speed  shield
viper               3       4
sidewinder          5       6

In [36]:
df.loc['cobra', 'shield']

2

In [38]:
df.loc['cobra':'sidewinder','shield']

cobra         2
viper         4
sidewinder    6
Name: shield, dtype: int64

In [45]:
print(df.loc[df['shield' ] >2,['max speed']])

            max speed
viper               3
sidewinder          5


In [47]:
df.loc[(df['shield']>2) & (df['max speed']>2),['max speed']]

max speed
viper               3
sidewinder          5

In [48]:

df.loc[lambda df:df['shield']==2]
# lambda applies where condition is required instead of using for loop or if statement use lambda in pandas

max speed  shield
cobra          1       2

In [50]:

df.loc[['viper','sidewinder'],['shield']]==3

shield
viper        False
sidewinder   False

# panel

In [15]:
import pandas as pd
import numpy as np
data = {'Item1' : pd.DataFrame(np.random.randn(4, 3)), 
   'Item2' : pd.DataFrame(np.random.randn(4, 2))}
P= pd.Panel(data)
P

C:\Users\Admin\Anaconda32\lib\site-packages\ipykernel_launcher.py:5: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  """


TypeError: Panel() takes no arguments

In [8]:
import time
time.ctime()
#to display current time

'Wed Mar  4 08:38:25 2020'

In [21]:
import pandas as pd
import numpy as np
data = {'Item1' : pd.DataFrame(np.random.randn(4, 3)), 
   'Item2' : pd.DataFrame(np.random.randn(4, 2))}
data
#p = pd.Panel(data)
#p['Item1']

{'Item1':           0         1         2
 0  0.398889  1.437483 -0.631660
 1  0.749307 -0.786200  1.939920
 2  0.461741  0.110466  0.349917
 3 -0.199384 -1.135897  0.102551, 'Item2':           0         1
 0  1.039239  0.345515
 1  0.363101 -0.465164
 2 -1.344589 -0.043884
 3  0.372300  1.266824}

# Data Cleansing

# check for missing values

In [22]:
import pandas as pd
import numpy as np

In [30]:
df=pd.DataFrame(np.random.randn(6,3),index=['a','b','c','d','e','f'],columns=['one','two','three'])
df=df.reindex(['a','b','c','d','e','f','g','h'])
print(df)

        one       two     three
a  1.157468 -0.223779  0.748283
b  0.210565  0.488348  0.561499
c -1.454407  1.429604  0.138963
d  0.177731 -0.778694  0.826489
e -1.253892 -0.945486 -0.807873
f -1.566981 -0.432705  0.826616
g       NaN       NaN       NaN
h       NaN       NaN       NaN


In [31]:
print(df.isnull())

     one    two  three
a  False  False  False
b  False  False  False
c  False  False  False
d  False  False  False
e  False  False  False
f  False  False  False
g   True   True   True
h   True   True   True


In [34]:
df.fillna(np.mean(df))
#most important mean function to fill missing values

one       two     three
a  1.157468 -0.223779  0.748283
b  0.210565  0.488348  0.561499
c -1.454407  1.429604  0.138963
d  0.177731 -0.778694  0.826489
e -1.253892 -0.945486 -0.807873
f -1.566981 -0.432705  0.826616
g -0.454920 -0.077118  0.382330
h -0.454920 -0.077118  0.382330

In [35]:
np.mean(df)

one     -0.454920
two     -0.077118
three    0.382330
dtype: float64

In [38]:
np.sum(df)

one     -2.729518
two     -0.462711
three    2.293979
dtype: float64

In [39]:
df.fillna(method='bfill')

one       two     three
a  1.157468 -0.223779  0.748283
b  0.210565  0.488348  0.561499
c -1.454407  1.429604  0.138963
d  0.177731 -0.778694  0.826489
e -1.253892 -0.945486 -0.807873
f -1.566981 -0.432705  0.826616
g       NaN       NaN       NaN
h       NaN       NaN       NaN

In [41]:
df.fillna(method='ffill')

one       two     three
a  1.157468 -0.223779  0.748283
b  0.210565  0.488348  0.561499
c -1.454407  1.429604  0.138963
d  0.177731 -0.778694  0.826489
e -1.253892 -0.945486 -0.807873
f -1.566981 -0.432705  0.826616
g -1.566981 -0.432705  0.826616
h -1.566981 -0.432705  0.826616

In [43]:
df

one       two     three
a  1.157468 -0.223779  0.748283
b  0.210565  0.488348  0.561499
c -1.454407  1.429604  0.138963
d  0.177731 -0.778694  0.826489
e -1.253892 -0.945486 -0.807873
f -1.566981 -0.432705  0.826616
g       NaN       NaN       NaN
h       NaN       NaN       NaN

In [44]:
df.dropna()

one       two     three
a  1.157468 -0.223779  0.748283
b  0.210565  0.488348  0.561499
c -1.454407  1.429604  0.138963
d  0.177731 -0.778694  0.826489
e -1.253892 -0.945486 -0.807873
f -1.566981 -0.432705  0.826616

In [45]:
df

one       two     three
a  1.157468 -0.223779  0.748283
b  0.210565  0.488348  0.561499
c -1.454407  1.429604  0.138963
d  0.177731 -0.778694  0.826489
e -1.253892 -0.945486 -0.807873
f -1.566981 -0.432705  0.826616
g       NaN       NaN       NaN
h       NaN       NaN       NaN

In [59]:
df=df.fillna(5)
# need to assign in df, as without assigning in df the values will change only in runtime not in dataframe

In [60]:
df.replace({5.000000: 1.000000})

one       two     three
a  1.157468 -0.223779  0.748283
b  0.210565  0.488348  0.561499
c -1.454407  1.429604  0.138963
d  0.177731 -0.778694  0.826489
e -1.253892 -0.945486 -0.807873
f -1.566981 -0.432705  0.826616
g  1.000000  1.000000  1.000000
h  1.000000  1.000000  1.000000

In [80]:
df=pd.read_csv('Weather.csv')
df

day         City  temperature  windspeed  event
0  01-01-2020    Ahmedabad           32          4   Rain
1  02-01-2020       Mumbai           35          5  Sunny
2  03-01-2020       Mumbai           34          4   Snow
3  04-01-2020  Gandhinagar           35          6  Sunny
4  05-01-2020    Ahmedabad           34          5  Sunny
5  06-01-2020  Gandhinagar           45          5   Snow

In [85]:
# to read specific row
df[0:3]

day       City  temperature  windspeed  event
0  01-01-2020  Ahmedabad           32          4   Rain
1  02-01-2020     Mumbai           35          5  Sunny
2  03-01-2020     Mumbai           34          4   Snow

In [81]:
# to read specific column
df[['City','temperature']]


City  temperature
0    Ahmedabad           32
1       Mumbai           35
2       Mumbai           34
3  Gandhinagar           35
4    Ahmedabad           34
5  Gandhinagar           45

In [100]:
df.loc[[1,3],['City','event']]
# to read row n column both


City  event
1       Mumbai  Sunny
3  Gandhinagar  Sunny

In [107]:
# to read rows to a certain range nd columns
df.loc[[1,4]['City']]

TypeError: list indices must be integers or slices, not str

# Data Wrangling

In [123]:
left = pd.DataFrame({
         'id':[1,2,3,4,5],
         'Name': ['Alex', 'Amy', 'Allen', 'Alice', 'Ayoung'],
         'subject_id':['sub1','sub2','sub4','sub6','sub5']})
right = pd.DataFrame(
         {'id':[1,2,3,4,5],
         'Name': ['Billy', 'Brian', 'Bran', 'Bryce', 'Betty'],
         'subject_id':['sub2','sub4','sub3','sub6','sub5']})
print(left)
print(right)

   id    Name subject_id
0   1    Alex       sub1
1   2     Amy       sub2
2   3   Allen       sub4
3   4   Alice       sub6
4   5  Ayoung       sub5
   id   Name subject_id
0   1  Billy       sub2
1   2  Brian       sub4
2   3   Bran       sub3
3   4  Bryce       sub6
4   5  Betty       sub5


In [132]:
df=pd.merge(left,right,how='inner',on='id')
df

id  Name_x subject_id_x Name_y subject_id_y
0   1    Alex         sub1  Billy         sub2
1   2     Amy         sub2  Brian         sub4
2   3   Allen         sub4   Bran         sub3
3   4   Alice         sub6  Bryce         sub6
4   5  Ayoung         sub5  Betty         sub5

In [127]:
print(pd.merge(left, right, how='inner', on='id',
left_index=False, right_index=False, sort=True))

   id  Name_x subject_id_x Name_y subject_id_y
0   1    Alex         sub1  Billy         sub2
1   2     Amy         sub2  Brian         sub4
2   3   Allen         sub4   Bran         sub3
3   4   Alice         sub6  Bryce         sub6
4   5  Ayoung         sub5  Betty         sub5


In [133]:
ipl_data = {'Team': ['Riders', 'Riders', 'Devils', 'Devils', 'Kings',
         'kings', 'Kings', 'Kings', 'Riders', 'Royals', 'Royals', 'Riders'],
         'Rank': [1, 2, 2, 3, 3,4 ,1 ,1,2 , 4,1,2],
         'Year': [2014,2015,2014,2015,2014,2015,2016,2017,2016,2014,2015,2017],
         'Points':[876,789,863,673,741,812,756,788,694,701,804,690]}
df = pd.DataFrame(ipl_data)
df

Team  Rank  Year  Points
0   Riders     1  2014     876
1   Riders     2  2015     789
2   Devils     2  2014     863
3   Devils     3  2015     673
4    Kings     3  2014     741
5    kings     4  2015     812
6    Kings     1  2016     756
7    Kings     1  2017     788
8   Riders     2  2016     694
9   Royals     4  2014     701
10  Royals     1  2015     804
11  Riders     2  2017     690

In [137]:
grouped=df.groupby('Year')
grouped.get_group(2014)
# get group for getting the value for particular group

Team  Rank  Year  Points
0  Riders     1  2014     876
2  Devils     2  2014     863
4   Kings     3  2014     741
9  Royals     4  2014     701

In [138]:
one = pd.DataFrame({
         'Name': ['Alex', 'Amy', 'Allen', 'Alice', 'Ayoung'],
         'subject_id':['sub1','sub2','sub4','sub6','sub5'],
         'Marks_scored':[98,90,87,69,78]},
         index=[1,2,3,4,5])
two = pd.DataFrame({
         'Name': ['Billy', 'Brian', 'Bran', 'Bryce', 'Betty'],
         'subject_id':['sub2','sub4','sub3','sub6','sub5'],
         'Marks_scored':[89,80,79,97,88]},
         index=[1,2,3,4,5])
print(one)
print(two)

     Name subject_id  Marks_scored
1    Alex       sub1            98
2     Amy       sub2            90
3   Allen       sub4            87
4   Alice       sub6            69
5  Ayoung       sub5            78
    Name subject_id  Marks_scored
1  Billy       sub2            89
2  Brian       sub4            80
3   Bran       sub3            79
4  Bryce       sub6            97
5  Betty       sub5            88


In [141]:
pd.concat([one,two],axis=1)

Name subject_id  Marks_scored   Name subject_id  Marks_scored
1    Alex       sub1            98  Billy       sub2            89
2     Amy       sub2            90  Brian       sub4            80
3   Allen       sub4            87   Bran       sub3            79
4   Alice       sub6            69  Bryce       sub6            97
5  Ayoung       sub5            78  Betty       sub5            88

In [143]:
df = pd.DataFrame(np.random.randn(10, 4),
      index = pd.date_range('1/1/2000', periods=10),
      columns = ['A', 'B', 'C', 'D'])

print (df)


                   A         B         C         D
2000-01-01 -0.176380 -0.402097 -0.289307 -0.816771
2000-01-02  1.317605 -0.681116 -0.123735  0.159979
2000-01-03  1.581706  0.352780  0.275556 -1.014102
2000-01-04  0.732915  0.252642  0.467237  0.558616
2000-01-05 -0.201757  0.066357  0.510173 -0.371304
2000-01-06 -0.467458 -0.264398  0.098142  0.039888
2000-01-07  1.678075 -2.120757 -1.789292  0.847730
2000-01-08  1.500330  1.145704  2.014317  0.237281
2000-01-09  1.211183  0.626772 -0.215850  1.354130
2000-01-10  0.267655  0.268527  1.152817 -0.797433


In [144]:
r=df.rolling(window=2,min_periods=1).sum()
r

A         B         C         D
2000-01-01 -0.176380 -0.402097 -0.289307 -0.816771
2000-01-02  1.141225 -1.083213 -0.413042 -0.656792
2000-01-03  2.899312 -0.328335  0.151820 -0.854123
2000-01-04  2.314622  0.605423  0.742793 -0.455486
2000-01-05  0.531158  0.318999  0.977410  0.187312
2000-01-06 -0.669215 -0.198041  0.608315 -0.331416
2000-01-07  1.210617 -2.385156 -1.691150  0.887618
2000-01-08  3.178405 -0.975053  0.225025  1.085011
2000-01-09  2.711513  1.772476  1.798468  1.591411
2000-01-10  1.478838  0.895299  0.936967  0.556696